<a href="https://colab.research.google.com/github/Udit2233/Udit_Mangal_Data-Science-and-vizulization/blob/main/Udit%20Mangal_Assignment_6_dataframes.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [2]:
data = {
    'Name': ['Aman', 'Riya', 'Rahul', 'Priya'],
    'Age': [20, 21, 19, 22],
    'City': ['Delhi', 'Mumbai', 'Pune', 'Agra']
}
student_df = pd.DataFrame(data)

In [3]:
student_df

    Name  Age    City
0   Aman   20   Delhi
1   Riya   21  Mumbai
2  Rahul   19    Pune
3  Priya   22    Agra

In [4]:
student_df.columns

Index(['Name', 'Age', 'City'], dtype='object')

In [5]:
student_df['Name']

0     Aman
1     Riya
2    Rahul
3    Priya
Name: Name, dtype: object

In [6]:
student_df['City']

0     Delhi
1    Mumbai
2      Pune
3      Agra
Name: City, dtype: object

In [7]:
new_df = student_df[['Name', 'City']]
new_df

    Name    City
0   Aman   Delhi
1   Riya  Mumbai
2  Rahul    Pune
3  Priya    Agra

In [8]:
data = {
    'Book': ['Python', 'Java', 'C++'],
    'Author': ['Amit', 'Rohit', 'Neha'],
    'Price': [400, 350, 300]
}
book_df = pd.DataFrame(data)
book_df

     Book Author  Price
0  Python   Amit    400
1    Java  Rohit    350
2     C++   Neha    300

In [9]:
book_df['Publisher'] = 'ABC Publications'
book_df

     Book Author  Price         Publisher
0  Python   Amit    400  ABC Publications
1    Java  Rohit    350  ABC Publications
2     C++   Neha    300  ABC Publications

In [10]:
df = pd.DataFrame({
    'Name': ['A', 'B', 'C', 'D', 'E']
})
df['SerialNo'] = np.arange(5)
df

  Name  SerialNo
0    A         0
1    B         1
2    C         2
3    D         3
4    E         4

In [11]:
del df['SerialNo']
df

  Name
0    A
1    B
2    C
3    D
4    E

In [12]:
data = {
    'Movie': ['3 Idiots', 'Dangal', 'PK'],
    'Year': [2009, 2016, 2014],
    'Rating': [8.4, 8.3, 8.1]
}
movie_df = pd.DataFrame(data)
movie_df

      Movie  Year  Rating
0  3 Idiots  2009     8.4
1    Dangal  2016     8.3
2        PK  2014     8.1

In [13]:
new_movie_df = pd.DataFrame(
    movie_df,
    columns=['Movie', 'Rating', 'Director']
)
new_movie_df

      Movie  Rating  Director
0  3 Idiots     8.4       NaN
1    Dangal     8.3       NaN
2        PK     8.1       NaN

In [14]:
city_series = pd.Series(
    ['Delhi', 'Mumbai'],
    index=[0, 3]
)
city_series

0     Delhi
3    Mumbai
dtype: object

In [15]:
branch_df = pd.DataFrame({
    'Student': ['Aman', 'Riya', 'Rahul', 'Priya']
})
branch_df['Branch'] = city_series
branch_df

  Student  Branch
0    Aman   Delhi
1    Riya     NaN
2   Rahul     NaN
3   Priya  Mumbai

In [18]:
data = {
    'Employee': ['Aman', 'Riya', 'Rahul', 'Priya', 'Neha'],
    'Department': ['IT', 'HR', 'Sales', 'IT', 'Finance'],
    'Experience': [2, 4, 3, 5, 1]
}
employee_df = pd.DataFrame(data)
new_df = employee_df[['Employee', 'Experience']]
new_df

  Employee  Experience
0     Aman           2
1     Riya           4
2    Rahul           3
3    Priya           5
4     Neha           1

In [19]:
employee_df['Department']

0         IT
1         HR
2      Sales
3         IT
4    Finance
Name: Department, dtype: object

In [20]:
employee_df.columns

Index(['Employee', 'Department', 'Experience'], dtype='object')

In [21]:
employee_df['Office'] = 'Head Office'

employee_df

  Employee Department  Experience       Office
0     Aman         IT           2  Head Office
1     Riya         HR           4  Head Office
2    Rahul      Sales           3  Head Office
3    Priya         IT           5  Head Office
4     Neha    Finance           1  Head Office

In [22]:
employee_df['Office'] = np.arange(5)

employee_df

  Employee Department  Experience  Office
0     Aman         IT           2       0
1     Riya         HR           4       1
2    Rahul      Sales           3       2
3    Priya         IT           5       3
4     Neha    Finance           1       4

In [23]:
office_names = pd.Series(
    ['Delhi', 'Mumbai', 'Pune'],
    index=[0, 2, 4]
)

employee_df['Office'] = office_names
employee_df

  Employee Department  Experience  Office
0     Aman         IT           2   Delhi
1     Riya         HR           4     NaN
2    Rahul      Sales           3  Mumbai
3    Priya         IT           5     NaN
4     Neha    Finance           1    Pune

In [24]:
del employee_df['Office']
employee_df

  Employee Department  Experience
0     Aman         IT           2
1     Riya         HR           4
2    Rahul      Sales           3
3    Priya         IT           5
4     Neha    Finance           1

In [25]:
data = {
    'Product': ['Laptop', 'Mobile', 'Tablet'],
    'Category': ['Electronics', 'Electronics', 'Electronics'],
    'Price': [50000, 20000, 15000]
}

product_df = pd.DataFrame(data)
new_product_df = product_df[['Price', 'Product', 'Category']]
new_product_df

   Price Product     Category
0  50000  Laptop  Electronics
1  20000  Mobile  Electronics
2  15000  Tablet  Electronics

In [26]:
data = {
    'Name': ['Aman', 'Riya', 'Rahul'],
    'Age': [20, 21, 19],
    'City': ['Delhi', 'Agra', 'Pune']
}

df = pd.DataFrame(data)
new_df = pd.DataFrame(
    df,
    columns=['Name', 'Age', 'City', 'Marks']
)
new_df

    Name  Age   City  Marks
0   Aman   20  Delhi    NaN
1   Riya   21   Agra    NaN
2  Rahul   19   Pune    NaN

In [27]:
data = {
    'Name': ['Aman', 'Riya', 'Rahul'],
    'Total Marks': [85, 90, 78]
}

df = pd.DataFrame(data)
df['Total Marks']

0    85
1    90
2    78
Name: Total Marks, dtype: int64

In [31]:
data = {
    'Student': ['Aman', 'Riya', 'Rahul', 'Priya', 'Neha'],
    'Course': ['Python', 'Java', 'C++', 'Python', 'Java'],
    'Score': [85, 90, 78, 88, 92]
}

course_df = pd.DataFrame(data)
course_df.columns

Index(['Student', 'Course', 'Score'], dtype='object')

In [32]:
course_df['Student']

0     Aman
1     Riya
2    Rahul
3    Priya
4     Neha
Name: Student, dtype: object

In [33]:
new_df = course_df[['Student', 'Score']]
new_df

  Student  Score
0    Aman     85
1    Riya     90
2   Rahul     78
3   Priya     88
4    Neha     92

In [34]:
course_df['Batch'] = '2026'
course_df

  Student  Course  Score Batch
0    Aman  Python     85  2026
1    Riya    Java     90  2026
2   Rahul     C++     78  2026
3   Priya  Python     88  2026
4    Neha    Java     92  2026

In [35]:
travel_df = pd.DataFrame({
    'Destination': ['Delhi', 'Agra', 'Jaipur', 'Mumbai', 'Pune']
})
travel_df['Code'] = np.arange(5)

travel_df

  Destination  Code
0       Delhi     0
1        Agra     1
2      Jaipur     2
3      Mumbai     3
4        Pune     4

In [36]:
code_series = pd.Series(
    [101, 104],
    index=[1, 4]
)
travel_df['Code'] = code_series

travel_df

  Destination   Code
0       Delhi    NaN
1        Agra  101.0
2      Jaipur    NaN
3      Mumbai    NaN
4        Pune  104.0

In [39]:
data = {
    'Student': ['Aman', 'Riya', 'Rahul', 'Priya', 'Neha'],
    'Class': [10, 10, 11, 11, 12],
    'Section': ['A', 'B', 'A', 'C', 'B']
}

school_df = pd.DataFrame(data)

In [38]:
new_df = pd.DataFrame(
    school_df,
    columns=['Student', 'Class', 'Section', 'House']
)
new_df

  Student  Class Section  House
0    Aman     10       A    NaN
1    Riya     10       B    NaN
2   Rahul     11       A    NaN
3   Priya     11       C    NaN
4    Neha     12       B    NaN

In [40]:
new_df['House'] = 'Red House'

new_df

  Student  Class Section      House
0    Aman     10       A  Red House
1    Riya     10       B  Red House
2   Rahul     11       A  Red House
3   Priya     11       C  Red House
4    Neha     12       B  Red House

In [41]:
data = {
    'Item': ['Pen', 'Book', 'Pencil', 'Bag', 'Scale'],
    'Price': [10, 50, 5, 300, 20],
    'Quantity': [100, 50, 200, 20, 80]
}

inventory_df = pd.DataFrame(data)

In [42]:
stock_series = pd.Series(
    [500, 200, 100],
    index=[0, 2, 4]
)
inventory_df['Stock'] = stock_series

inventory_df

     Item  Price  Quantity  Stock
0     Pen     10       100  500.0
1    Book     50        50    NaN
2  Pencil      5       200  200.0
3     Bag    300        20    NaN
4   Scale     20        80  100.0

In [43]:
del inventory_df['Stock']

inventory_df

     Item  Price  Quantity
0     Pen     10       100
1    Book     50        50
2  Pencil      5       200
3     Bag    300        20
4   Scale     20        80

In [46]:
s = pd.Series(['Delhi', 'Pune'], index=[0, 3])

df = pd.DataFrame({
    'Name': ['Aman', 'Riya', 'Rahul', 'Priya']
})

df['City'] = s

df

    Name   City
0   Aman  Delhi
1   Riya    NaN
2  Rahul    NaN
3  Priya   Pune